#!/bin/bash

[[ $( command -v shellcheck ) ]] || { echo error: shellcheck required; exit 1; }

shellcheck --exclude=SC1091,SC2086 /a/script/build
shellcheck --exclude=SC1091,SC2086 /a/script/run
shellcheck --exclude=SC1091,SC2086 /a/script/publish

echo ok
