#!/bin/bash

set -o errexit

[[ $( command -v xxhsum ) ]] || { echo error: xxhsum required; exit 1; }

find /a/local/data -type f -print0 | xargs -0 xxhsum | sed 's|A:/local/data||' | awk '{print "mkdir --parents /a/local/archive/data/"$2" && cp /a/local/data/"$2" /a/local/archive/data/"$2"/"$1}' | bash
find /a/local/tool -type f -print0 | xargs -0 xxhsum | sed 's|A:/local/tool||' | awk '{print "mkdir --parents /a/local/archive/tool/"$2" && cp /a/local/tool/"$2" /a/local/archive/tool/"$2"/"$1}' | bash
find /a/local/archive -type f | sed 's|/a/local/archive/||' > /a/local/index/archive.txt
code --diff /a/index/archive.txt /a/local/index/archive.txt
