#!/bin/bash

set -o errexit

[[ $( command -v xxhsum ) ]] || { echo error: xxhsum required; exit 1; }

find /a/local/tool -type f -print0 | xargs -0 xxhsum | sed "s|A:/local/tool/||" > /a/local/index/tool.txt
code --diff /a/index/tool.txt /a/local/index/tool.txt
