#!/bin/bash

set -o errexit

[[ $( command -v butler ) ]] || { echo error: butler required; exit 1; }

clear

#

mode=${1:-"staging"}

[[ $mode == "staging" || $mode == "production" ]] || {
	echo error: unrecognized mode "$mode"
	exit 1
}

#

rm --recursive --force /a/local/publish/$mode
mkdir --parents $_
cd $_

[[ $mode == "staging" ]] && {
	build debug
	build profile
}

build release

[[ $mode == "staging" ]] && {
	cp /a/local/build/debug/dread_check.exe   ./dread_check_debug.exe
	cp /a/local/build/profile/dread_check.exe ./dread_check_profile.exe
	cp /a/local/vend/bin/ds5w_X64.dll .
}

cp /a/local/build/release/dread_check.exe .
cp /a/static/.itch.toml              .
cp --recursive /a/local/build/release/data ./data

butler validate /a/local/publish/$mode

[[ $mode == "staging"    ]] && butler push /a/local/publish/staging    "belimoth/dread-check-staging:windows"
[[ $mode == "production" ]] && butler push /a/local/publish/production "belimoth/dread-check:windows"
