#!/bin/bash

set -o errexit

[[ $SHLVL -gt 2 ]] || clear

echo running...

#

[[ -d /a/local/data ]] || { echo error: missing data; exit 1; }

rm --recursive --force /a/local/run
mkdir --parents $_
cd $_

rm --recursive --force   /a/local/data/shader
cp --recursive /a/shader /a/local/data

ln --symbolic /a/local/data                          .
ln --symbolic /a/local/vend/bin/ds5w_x64.dll         .
ln --symbolic /a/local/vend/bin/discord_game_sdk.dll .

/a/local/build/profile/draugb.exe "$@"
