#!/bin/bash

set -o errexit

[[ $SHLVL -gt 2 ]] || clear

echo vending...

#

# rm --recursive --force /a/local/vend/include

  cp                       /a/local/vcpkg/installed/x64-windows-static/include/argh.h       /a/local/vend/include/argh/argh.h
  cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/curl         /a/local/vend/include/curl
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/brotlicommon.lib /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/brotlidec.lib    /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/brotlienc.lib    /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/cpprest_2_10.lib /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/inireader.lib    /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/libcurl.lib      /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/presentdata.lib  /a/local/vend/lib
  cp                       /a/local/vcpkg/installed/x64-windows-static/lib/zlib.lib         /a/local/vend/lib
  cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/directxtk    /a/local/vend/include/directxtk
# cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/directxtex   /a/local/vend/include/directxtex
# cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/discord      /a/local/vend/include/discord
# cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/ds5w         /a/local/vend/include/ds5w
# cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/dxh          /a/local/vend/include/dxh
  cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/enet         /a/local/vend/include/enet
  cp --recursive --parents /a/local/vcpkg/installed/x64-windows-static/include/inih         /a/local/vend/include/inih

# todo
