#!/bin/bash

set -o errexit

[[ $( command -v xxhsum ) ]] || { echo error: xxhsum required; exit 1; }

cd /z/belimoth/data/draugb/data
mkdir --parents /a/local/index/archive
find . -type f -print0 | xargs -0 xxhsum > /a/local/index/archive/data.txt

cd /a/local/data
find . -type f -print0 | xargs -0 xxhsum > /a/local/index/data.txt

code --diff /a/local/index/archive/data.txt /a/local/index/data.txt
