#!/bin/bash

set -o errexit

git remote show origin > /dev/null && git remote rm origin
git remote add                  origin git@github.com:subhelion/dread_check.git
git remote set-url --add --push origin git@github.com:subhelion/dread_check.git
git remote set-url --add --push origin git@github.com:belimoth/dread_check.git
